[package]
name = "bcp-render"
description = "QR, SVG, bitmap and plate layouts for bcp"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
bcp-core = { version = "0.1.0", path = "../bcp-core" }
qrcode.workspace = true

[dev-dependencies]
rxing.workspace = true
serde.workspace = true
serde_json.workspace = true
