[package]
name = "bcp-app"
description = "The bcp command line tool and GUI"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "bcp"
path = "src/main.rs"

[features]
gui = []

[dependencies]
bcp-core = { version = "0.1.0", path = "../bcp-core" }
bcp-render = { version = "0.1.0", path = "../bcp-render" }
bcp-scan = { version = "0.1.0", path = "../bcp-scan" }
clap.workspace = true
rpassword.workspace = true
sha2.workspace = true
zeroize.workspace = true

[dev-dependencies]
serde_json.workspace = true
